//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 11:45:01 PM GMT 
//


package com.nktin.protocol;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for country.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="country">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AT"/>
 *     &lt;enumeration value="AU"/>
 *     &lt;enumeration value="BE"/>
 *     &lt;enumeration value="CA"/>
 *     &lt;enumeration value="CN"/>
 *     &lt;enumeration value="DE"/>
 *     &lt;enumeration value="EU"/>
 *     &lt;enumeration value="FR"/>
 *     &lt;enumeration value="IT"/>
 *     &lt;enumeration value="JP"/>
 *     &lt;enumeration value="NO"/>
 *     &lt;enumeration value="NZ"/>
 *     &lt;enumeration value="PL"/>
 *     &lt;enumeration value="RU"/>
 *     &lt;enumeration value="UK"/>
 *     &lt;enumeration value="US"/>
 *     &lt;enumeration value="CH"/>
 *     &lt;enumeration value="RO"/>
 *     &lt;enumeration value="SE"/>
 *     &lt;enumeration value="ANY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "country")
@XmlEnum
public enum Country {

    AT,
    AU,
    BE,
    CA,
    CN,
    DE,
    EU,
    FR,
    IT,
    JP,
    NO,
    NZ,
    PL,
    RU,
    UK,
    US,
    CH,
    RO,
    SE,
    ANY;

    public String value() {
        return name();
    }

    public static Country fromValue(String v) {
        return valueOf(v);
    }

}
