//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 11:45:01 PM GMT 
//


package com.nktin.protocol;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for field_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="field_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="float"/>
 *     &lt;enumeration value="float-range"/>
 *     &lt;enumeration value="short"/>
 *     &lt;enumeration value="long"/>
 *     &lt;enumeration value="double"/>
 *     &lt;enumeration value="date"/>
 *     &lt;enumeration value="boolean"/>
 *     &lt;enumeration value="yes_no_na"/>
 *     &lt;enumeration value="directional"/>
 *     &lt;enumeration value="int"/>
 *     &lt;enumeration value="time"/>
 *     &lt;enumeration value="timeframe"/>
 *     &lt;enumeration value="enumeration"/>
 *     &lt;enumeration value="iso_country_code"/>
 *     &lt;enumeration value="short_value_enumeration"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "field_type")
@XmlEnum
public enum FieldType {

    @XmlEnumValue("float")
    FLOAT("float"),
    @XmlEnumValue("float-range")
    FLOAT_RANGE("float-range"),
    @XmlEnumValue("short")
    SHORT("short"),
    @XmlEnumValue("long")
    LONG("long"),
    @XmlEnumValue("double")
    DOUBLE("double"),
    @XmlEnumValue("date")
    DATE("date"),
    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),
    @XmlEnumValue("yes_no_na")
    YES_NO_NA("yes_no_na"),
    @XmlEnumValue("directional")
    DIRECTIONAL("directional"),
    @XmlEnumValue("int")
    INT("int"),
    @XmlEnumValue("time")
    TIME("time"),
    @XmlEnumValue("timeframe")
    TIMEFRAME("timeframe"),
    @XmlEnumValue("enumeration")
    ENUMERATION("enumeration"),
    @XmlEnumValue("iso_country_code")
    ISO_COUNTRY_CODE("iso_country_code"),
    @XmlEnumValue("short_value_enumeration")
    SHORT_VALUE_ENUMERATION("short_value_enumeration");
    private final String value;

    FieldType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FieldType fromValue(String v) {
        for (FieldType c: FieldType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
