//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 11:45:01 PM GMT 
//


package com.nktin.protocol;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for multicast_group.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="multicast_group">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SYSTEM_HEARTBEAT"/>
 *     &lt;enumeration value="US_DEPT_LABOR"/>
 *     &lt;enumeration value="US_DEPT_COMMERCE"/>
 *     &lt;enumeration value="US_DEPT_TREASURY"/>
 *     &lt;enumeration value="US_DEPT_AGRICULTURE"/>
 *     &lt;enumeration value="US_NATL_ASSOC_REALTORS"/>
 *     &lt;enumeration value="US_GROUP_1"/>
 *     &lt;enumeration value="US_GROUP_2"/>
 *     &lt;enumeration value="US_GROUP_3"/>
 *     &lt;enumeration value="US_GROUP_4"/>
 *     &lt;enumeration value="US_CORP_NEWS"/>
 *     &lt;enumeration value="US_FED"/>
 *     &lt;enumeration value="US_ESTIMATES"/>
 *     &lt;enumeration value="UK_OFC_NATL_STATISTICS"/>
 *     &lt;enumeration value="EU_ESTIMATES"/>
 *     &lt;enumeration value="EU_GROUP_1"/>
 *     &lt;enumeration value="EU_GROUP_2"/>
 *     &lt;enumeration value="EU_GROUP_3"/>
 *     &lt;enumeration value="UK_BOE"/>
 *     &lt;enumeration value="UK_ESTIMATES"/>
 *     &lt;enumeration value="DE_ESTIMATES"/>
 *     &lt;enumeration value="CA_STATISTICS_CANADA"/>
 *     &lt;enumeration value="CA_BANK_OF_CANADA"/>
 *     &lt;enumeration value="CA_GROUP_1"/>
 *     &lt;enumeration value="CA_GROUP_2"/>
 *     &lt;enumeration value="CA_ESTIMATES"/>
 *     &lt;enumeration value="BETA_1"/>
 *     &lt;enumeration value="BETA_2"/>
 *     &lt;enumeration value="BETA_3"/>
 *     &lt;enumeration value="BETA_4"/>
 *     &lt;enumeration value="BETA_5"/>
 *     &lt;enumeration value="BETA_6"/>
 *     &lt;enumeration value="BETA_7"/>
 *     &lt;enumeration value="BETA_8"/>
 *     &lt;enumeration value="BETA_9"/>
 *     &lt;enumeration value="BETA_10"/>
 *     &lt;enumeration value="ASIAPAC"/>
 *     &lt;enumeration value="ASIAPAC_ESTIMATES"/>
 *     &lt;enumeration value="GTA"/>
 *     &lt;enumeration value="GTA_ESTIMATES"/>
 *     &lt;enumeration value="CHI_REPORT"/>
 *     &lt;enumeration value="FITCH"/>
 *     &lt;enumeration value="RISK_NOTIFICATION"/>
 *     &lt;enumeration value="ISM"/>
 *     &lt;enumeration value="*ANY*"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "multicast_group")
@XmlEnum
public enum MulticastGroup {

    SYSTEM_HEARTBEAT("SYSTEM_HEARTBEAT"),
    US_DEPT_LABOR("US_DEPT_LABOR"),
    US_DEPT_COMMERCE("US_DEPT_COMMERCE"),
    US_DEPT_TREASURY("US_DEPT_TREASURY"),
    US_DEPT_AGRICULTURE("US_DEPT_AGRICULTURE"),
    US_NATL_ASSOC_REALTORS("US_NATL_ASSOC_REALTORS"),
    US_GROUP_1("US_GROUP_1"),
    US_GROUP_2("US_GROUP_2"),
    US_GROUP_3("US_GROUP_3"),
    US_GROUP_4("US_GROUP_4"),
    US_CORP_NEWS("US_CORP_NEWS"),
    US_FED("US_FED"),
    US_ESTIMATES("US_ESTIMATES"),
    UK_OFC_NATL_STATISTICS("UK_OFC_NATL_STATISTICS"),
    EU_ESTIMATES("EU_ESTIMATES"),
    EU_GROUP_1("EU_GROUP_1"),
    EU_GROUP_2("EU_GROUP_2"),
    EU_GROUP_3("EU_GROUP_3"),
    UK_BOE("UK_BOE"),
    UK_ESTIMATES("UK_ESTIMATES"),
    DE_ESTIMATES("DE_ESTIMATES"),
    CA_STATISTICS_CANADA("CA_STATISTICS_CANADA"),
    CA_BANK_OF_CANADA("CA_BANK_OF_CANADA"),
    CA_GROUP_1("CA_GROUP_1"),
    CA_GROUP_2("CA_GROUP_2"),
    CA_ESTIMATES("CA_ESTIMATES"),
    BETA_1("BETA_1"),
    BETA_2("BETA_2"),
    BETA_3("BETA_3"),
    BETA_4("BETA_4"),
    BETA_5("BETA_5"),
    BETA_6("BETA_6"),
    BETA_7("BETA_7"),
    BETA_8("BETA_8"),
    BETA_9("BETA_9"),
    BETA_10("BETA_10"),
    ASIAPAC("ASIAPAC"),
    ASIAPAC_ESTIMATES("ASIAPAC_ESTIMATES"),
    GTA("GTA"),
    GTA_ESTIMATES("GTA_ESTIMATES"),
    CHI_REPORT("CHI_REPORT"),
    FITCH("FITCH"),
    RISK_NOTIFICATION("RISK_NOTIFICATION"),
    ISM("ISM"),
    @XmlEnumValue("*ANY*")
    ANY("*ANY*");
    private final String value;

    MulticastGroup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MulticastGroup fromValue(String v) {
        for (MulticastGroup c: MulticastGroup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
