//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 11:45:01 PM GMT 
//


package com.nktin.protocol;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProtocolCategoryDataDatumOptionalNumeric_QNAME = new QName("", "optional_numeric");
    private final static QName _ProtocolCategoryDataDatumDatumId_QNAME = new QName("", "datum_id");
    private final static QName _ProtocolCategoryDataDatumShortDescription_QNAME = new QName("", "short_description");
    private final static QName _ProtocolCategoryDataDatumDatumType_QNAME = new QName("", "datum_type");
    private final static QName _ProtocolCategoryDataDatumDescription_QNAME = new QName("", "description");
    private final static QName _ProtocolCategoryDataDatumDatumScale_QNAME = new QName("", "datum_scale");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Protocol }
     * 
     */
    public Protocol createProtocol() {
        return new Protocol();
    }

    /**
     * Create an instance of {@link Protocol.Category }
     * 
     */
    public Protocol.Category createProtocolCategory() {
        return new Protocol.Category();
    }

    /**
     * Create an instance of {@link Protocol.Category.Messages }
     * 
     */
    public Protocol.Category.Messages createProtocolCategoryMessages() {
        return new Protocol.Category.Messages();
    }

    /**
     * Create an instance of {@link Protocol.Category.Messages.Message }
     * 
     */
    public Protocol.Category.Messages.Message createProtocolCategoryMessagesMessage() {
        return new Protocol.Category.Messages.Message();
    }

    /**
     * Create an instance of {@link Protocol.Category.Messages.Message.Fields }
     * 
     */
    public Protocol.Category.Messages.Message.Fields createProtocolCategoryMessagesMessageFields() {
        return new Protocol.Category.Messages.Message.Fields();
    }

    /**
     * Create an instance of {@link Protocol.Category.Messages.Message.Fields.Field }
     * 
     */
    public Protocol.Category.Messages.Message.Fields.Field createProtocolCategoryMessagesMessageFieldsField() {
        return new Protocol.Category.Messages.Message.Fields.Field();
    }

    /**
     * Create an instance of {@link Protocol.Category.Messages.Message.Fields.Field.AllowedValues }
     * 
     */
    public Protocol.Category.Messages.Message.Fields.Field.AllowedValues createProtocolCategoryMessagesMessageFieldsFieldAllowedValues() {
        return new Protocol.Category.Messages.Message.Fields.Field.AllowedValues();
    }

    /**
     * Create an instance of {@link Protocol.Category.Data }
     * 
     */
    public Protocol.Category.Data createProtocolCategoryData() {
        return new Protocol.Category.Data();
    }

    /**
     * Create an instance of {@link Protocol.Revisions }
     * 
     */
    public Protocol.Revisions createProtocolRevisions() {
        return new Protocol.Revisions();
    }

    /**
     * Create an instance of {@link Protocol.Category.Messages.Message.Fields.Field.AllowedValues.AllowedValue }
     * 
     */
    public Protocol.Category.Messages.Message.Fields.Field.AllowedValues.AllowedValue createProtocolCategoryMessagesMessageFieldsFieldAllowedValuesAllowedValue() {
        return new Protocol.Category.Messages.Message.Fields.Field.AllowedValues.AllowedValue();
    }

    /**
     * Create an instance of {@link Protocol.Category.Data.Datum }
     * 
     */
    public Protocol.Category.Data.Datum createProtocolCategoryDataDatum() {
        return new Protocol.Category.Data.Datum();
    }

    /**
     * Create an instance of {@link Protocol.Revisions.Revision }
     * 
     */
    public Protocol.Revisions.Revision createProtocolRevisionsRevision() {
        return new Protocol.Revisions.Revision();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "optional_numeric", scope = Protocol.Category.Data.Datum.class)
    public JAXBElement<Boolean> createProtocolCategoryDataDatumOptionalNumeric(Boolean value) {
        return new JAXBElement<Boolean>(_ProtocolCategoryDataDatumOptionalNumeric_QNAME, Boolean.class, Protocol.Category.Data.Datum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datum_id", scope = Protocol.Category.Data.Datum.class)
    public JAXBElement<Integer> createProtocolCategoryDataDatumDatumId(Integer value) {
        return new JAXBElement<Integer>(_ProtocolCategoryDataDatumDatumId_QNAME, Integer.class, Protocol.Category.Data.Datum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "short_description", scope = Protocol.Category.Data.Datum.class)
    public JAXBElement<String> createProtocolCategoryDataDatumShortDescription(String value) {
        return new JAXBElement<String>(_ProtocolCategoryDataDatumShortDescription_QNAME, String.class, Protocol.Category.Data.Datum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datum_type", scope = Protocol.Category.Data.Datum.class)
    public JAXBElement<String> createProtocolCategoryDataDatumDatumType(String value) {
        return new JAXBElement<String>(_ProtocolCategoryDataDatumDatumType_QNAME, String.class, Protocol.Category.Data.Datum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description", scope = Protocol.Category.Data.Datum.class)
    public JAXBElement<String> createProtocolCategoryDataDatumDescription(String value) {
        return new JAXBElement<String>(_ProtocolCategoryDataDatumDescription_QNAME, String.class, Protocol.Category.Data.Datum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatumScale }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datum_scale", scope = Protocol.Category.Data.Datum.class)
    public JAXBElement<DatumScale> createProtocolCategoryDataDatumDatumScale(DatumScale value) {
        return new JAXBElement<DatumScale>(_ProtocolCategoryDataDatumDatumScale_QNAME, DatumScale.class, Protocol.Category.Data.Datum.class, value);
    }

}
