//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 11:45:01 PM GMT 
//


package com.nktin.protocol;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="revisions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="revision" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="author" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="category" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country" type="{}country"/>
 *                   &lt;element name="category_id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="data">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="datum" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;choice maxOccurs="unbounded">
 *                                         &lt;element name="short_description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                         &lt;element name="datum_scale" type="{}datum_scale"/>
 *                                         &lt;element name="datum_type" type="{}datum_type"/>
 *                                         &lt;element name="datum_id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                                         &lt;element name="optional_numeric" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                                       &lt;/choice>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="messages" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="message" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="message_type" type="{}message_type"/>
 *                                       &lt;element name="message_version" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                       &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                                       &lt;element name="multicast_group" type="{}multicast_group"/>
 *                                       &lt;element name="fields">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="field" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="datum_id" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                                           &lt;element name="field_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="example_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="allowed_values" minOccurs="0">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="allowed_value" maxOccurs="unbounded" minOccurs="0">
 *                                                                       &lt;complexType>
 *                                                                         &lt;complexContent>
 *                                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                             &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                                             &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                                           &lt;/restriction>
 *                                                                         &lt;/complexContent>
 *                                                                       &lt;/complexType>
 *                                                                     &lt;/element>
 *                                                                   &lt;/sequence>
 *                                                                   &lt;attGroup ref="{}allowed_values_attributes"/>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "revisions",
    "category"
})
@XmlRootElement(name = "protocol")
public class Protocol {

    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected Protocol.Revisions revisions;
    @XmlElement(required = true)
    protected List<Protocol.Category> category;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the revisions property.
     * 
     * @return
     *     possible object is
     *     {@link Protocol.Revisions }
     *     
     */
    public Protocol.Revisions getRevisions() {
        return revisions;
    }

    /**
     * Sets the value of the revisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Protocol.Revisions }
     *     
     */
    public void setRevisions(Protocol.Revisions value) {
        this.revisions = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Protocol.Category }
     * 
     * 
     */
    public List<Protocol.Category> getCategory() {
        if (category == null) {
            category = new ArrayList<Protocol.Category>();
        }
        return this.category;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="country" type="{}country"/>
     *         &lt;element name="category_id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="data">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="datum" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;choice maxOccurs="unbounded">
     *                               &lt;element name="short_description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                               &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                               &lt;element name="datum_scale" type="{}datum_scale"/>
     *                               &lt;element name="datum_type" type="{}datum_type"/>
     *                               &lt;element name="datum_id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *                               &lt;element name="optional_numeric" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                             &lt;/choice>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="messages" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="message" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="message_type" type="{}message_type"/>
     *                             &lt;element name="message_version" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                             &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                             &lt;element name="multicast_group" type="{}multicast_group"/>
     *                             &lt;element name="fields">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="field" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="datum_id" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                                                 &lt;element name="field_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="example_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="allowed_values" minOccurs="0">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="allowed_value" maxOccurs="unbounded" minOccurs="0">
     *                                                             &lt;complexType>
     *                                                               &lt;complexContent>
     *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                                   &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                                                   &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                                                 &lt;/restriction>
     *                                                               &lt;/complexContent>
     *                                                             &lt;/complexType>
     *                                                           &lt;/element>
     *                                                         &lt;/sequence>
     *                                                         &lt;attGroup ref="{}allowed_values_attributes"/>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "country",
        "categoryId",
        "data",
        "messages"
    })
    public static class Category {

        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected Country country;
        @XmlElement(name = "category_id")
        @XmlSchemaType(name = "unsignedShort")
        protected int categoryId;
        @XmlElement(required = true)
        protected Protocol.Category.Data data;
        protected Protocol.Category.Messages messages;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link Country }
         *     
         */
        public Country getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link Country }
         *     
         */
        public void setCountry(Country value) {
            this.country = value;
        }

        /**
         * Gets the value of the categoryId property.
         * 
         */
        public int getCategoryId() {
            return categoryId;
        }

        /**
         * Sets the value of the categoryId property.
         * 
         */
        public void setCategoryId(int value) {
            this.categoryId = value;
        }

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link Protocol.Category.Data }
         *     
         */
        public Protocol.Category.Data getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link Protocol.Category.Data }
         *     
         */
        public void setData(Protocol.Category.Data value) {
            this.data = value;
        }

        /**
         * Gets the value of the messages property.
         * 
         * @return
         *     possible object is
         *     {@link Protocol.Category.Messages }
         *     
         */
        public Protocol.Category.Messages getMessages() {
            return messages;
        }

        /**
         * Sets the value of the messages property.
         * 
         * @param value
         *     allowed object is
         *     {@link Protocol.Category.Messages }
         *     
         */
        public void setMessages(Protocol.Category.Messages value) {
            this.messages = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="datum" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;choice maxOccurs="unbounded">
         *                     &lt;element name="short_description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                     &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                     &lt;element name="datum_scale" type="{}datum_scale"/>
         *                     &lt;element name="datum_type" type="{}datum_type"/>
         *                     &lt;element name="datum_id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
         *                     &lt;element name="optional_numeric" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *                   &lt;/choice>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "datum"
        })
        public static class Data {

            @XmlElement(required = true)
            protected List<Protocol.Category.Data.Datum> datum;

            /**
             * Gets the value of the datum property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the datum property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDatum().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Protocol.Category.Data.Datum }
             * 
             * 
             */
            public List<Protocol.Category.Data.Datum> getDatum() {
                if (datum == null) {
                    datum = new ArrayList<Protocol.Category.Data.Datum>();
                }
                return this.datum;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;choice maxOccurs="unbounded">
             *           &lt;element name="short_description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *           &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *           &lt;element name="datum_scale" type="{}datum_scale"/>
             *           &lt;element name="datum_type" type="{}datum_type"/>
             *           &lt;element name="datum_id" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
             *           &lt;element name="optional_numeric" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
             *         &lt;/choice>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "shortDescriptionOrDescriptionOrDatumScale"
            })
            public static class Datum {

                @XmlElementRefs({
                    @XmlElementRef(name = "datum_type", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "description", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "datum_id", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "optional_numeric", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "datum_scale", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "short_description", type = JAXBElement.class, required = false)
                })
                protected List<JAXBElement<?>> shortDescriptionOrDescriptionOrDatumScale;

                /**
                 * Gets the value of the shortDescriptionOrDescriptionOrDatumScale property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the shortDescriptionOrDescriptionOrDatumScale property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getShortDescriptionOrDescriptionOrDatumScale().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link Integer }{@code >}
                 * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
                 * {@link JAXBElement }{@code <}{@link DatumScale }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * 
                 * 
                 */
                public List<JAXBElement<?>> getShortDescriptionOrDescriptionOrDatumScale() {
                    if (shortDescriptionOrDescriptionOrDatumScale == null) {
                        shortDescriptionOrDescriptionOrDatumScale = new ArrayList<JAXBElement<?>>();
                    }
                    return this.shortDescriptionOrDescriptionOrDatumScale;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="message" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="message_type" type="{}message_type"/>
         *                   &lt;element name="message_version" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                   &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *                   &lt;element name="multicast_group" type="{}multicast_group"/>
         *                   &lt;element name="fields">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="field" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="datum_id" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                                       &lt;element name="field_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="example_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="allowed_values" minOccurs="0">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="allowed_value" maxOccurs="unbounded" minOccurs="0">
         *                                                   &lt;complexType>
         *                                                     &lt;complexContent>
         *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                                         &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                                         &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                                       &lt;/restriction>
         *                                                     &lt;/complexContent>
         *                                                   &lt;/complexType>
         *                                                 &lt;/element>
         *                                               &lt;/sequence>
         *                                               &lt;attGroup ref="{}allowed_values_attributes"/>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "message"
        })
        public static class Messages {

            @XmlElement(required = true)
            protected List<Protocol.Category.Messages.Message> message;

            /**
             * Gets the value of the message property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the message property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMessage().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Protocol.Category.Messages.Message }
             * 
             * 
             */
            public List<Protocol.Category.Messages.Message> getMessage() {
                if (message == null) {
                    message = new ArrayList<Protocol.Category.Messages.Message>();
                }
                return this.message;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="message_type" type="{}message_type"/>
             *         &lt;element name="message_version" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *         &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
             *         &lt;element name="multicast_group" type="{}multicast_group"/>
             *         &lt;element name="fields">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="field" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="datum_id" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *                             &lt;element name="field_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="example_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="allowed_values" minOccurs="0">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="allowed_value" maxOccurs="unbounded" minOccurs="0">
             *                                         &lt;complexType>
             *                                           &lt;complexContent>
             *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                               &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                                               &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                                             &lt;/restriction>
             *                                           &lt;/complexContent>
             *                                         &lt;/complexType>
             *                                       &lt;/element>
             *                                     &lt;/sequence>
             *                                     &lt;attGroup ref="{}allowed_values_attributes"/>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "messageType",
                "messageVersion",
                "startDate",
                "multicastGroup",
                "fields"
            })
            public static class Message {

                @XmlElement(name = "message_type", required = true)
                protected MessageType messageType;
                @XmlElement(name = "message_version")
                @XmlSchemaType(name = "unsignedByte")
                protected short messageVersion;
                @XmlElement(name = "start_date")
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar startDate;
                @XmlElement(name = "multicast_group", required = true)
                protected MulticastGroup multicastGroup;
                @XmlElement(required = true)
                protected Protocol.Category.Messages.Message.Fields fields;

                /**
                 * Gets the value of the messageType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MessageType }
                 *     
                 */
                public MessageType getMessageType() {
                    return messageType;
                }

                /**
                 * Sets the value of the messageType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MessageType }
                 *     
                 */
                public void setMessageType(MessageType value) {
                    this.messageType = value;
                }

                /**
                 * Gets the value of the messageVersion property.
                 * 
                 */
                public short getMessageVersion() {
                    return messageVersion;
                }

                /**
                 * Sets the value of the messageVersion property.
                 * 
                 */
                public void setMessageVersion(short value) {
                    this.messageVersion = value;
                }

                /**
                 * Gets the value of the startDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getStartDate() {
                    return startDate;
                }

                /**
                 * Sets the value of the startDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setStartDate(XMLGregorianCalendar value) {
                    this.startDate = value;
                }

                /**
                 * Gets the value of the multicastGroup property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MulticastGroup }
                 *     
                 */
                public MulticastGroup getMulticastGroup() {
                    return multicastGroup;
                }

                /**
                 * Sets the value of the multicastGroup property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MulticastGroup }
                 *     
                 */
                public void setMulticastGroup(MulticastGroup value) {
                    this.multicastGroup = value;
                }

                /**
                 * Gets the value of the fields property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Protocol.Category.Messages.Message.Fields }
                 *     
                 */
                public Protocol.Category.Messages.Message.Fields getFields() {
                    return fields;
                }

                /**
                 * Sets the value of the fields property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Protocol.Category.Messages.Message.Fields }
                 *     
                 */
                public void setFields(Protocol.Category.Messages.Message.Fields value) {
                    this.fields = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="field" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="datum_id" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                 *                   &lt;element name="field_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="example_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="allowed_values" minOccurs="0">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="allowed_value" maxOccurs="unbounded" minOccurs="0">
                 *                               &lt;complexType>
                 *                                 &lt;complexContent>
                 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                                     &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                                     &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                                   &lt;/restriction>
                 *                                 &lt;/complexContent>
                 *                               &lt;/complexType>
                 *                             &lt;/element>
                 *                           &lt;/sequence>
                 *                           &lt;attGroup ref="{}allowed_values_attributes"/>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "field"
                })
                public static class Fields {

                    @XmlElement(required = true)
                    protected List<Protocol.Category.Messages.Message.Fields.Field> field;

                    /**
                     * Gets the value of the field property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the field property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getField().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Protocol.Category.Messages.Message.Fields.Field }
                     * 
                     * 
                     */
                    public List<Protocol.Category.Messages.Message.Fields.Field> getField() {
                        if (field == null) {
                            field = new ArrayList<Protocol.Category.Messages.Message.Fields.Field>();
                        }
                        return this.field;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="datum_id" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                     *         &lt;element name="field_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="example_value" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="allowed_values" minOccurs="0">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="allowed_value" maxOccurs="unbounded" minOccurs="0">
                     *                     &lt;complexType>
                     *                       &lt;complexContent>
                     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *                           &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *                         &lt;/restriction>
                     *                       &lt;/complexContent>
                     *                     &lt;/complexType>
                     *                   &lt;/element>
                     *                 &lt;/sequence>
                     *                 &lt;attGroup ref="{}allowed_values_attributes"/>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "datumId",
                        "fieldType",
                        "exampleValue",
                        "allowedValues"
                    })
                    public static class Field {

                        @XmlElement(name = "datum_id")
                        @XmlSchemaType(name = "unsignedByte")
                        protected short datumId;
                        @XmlElement(name = "field_type", required = true)
                        protected String fieldType;
                        @XmlElement(name = "example_value", required = true)
                        protected String exampleValue;
                        @XmlElement(name = "allowed_values")
                        protected Protocol.Category.Messages.Message.Fields.Field.AllowedValues allowedValues;

                        /**
                         * Gets the value of the datumId property.
                         * 
                         */
                        public short getDatumId() {
                            return datumId;
                        }

                        /**
                         * Sets the value of the datumId property.
                         * 
                         */
                        public void setDatumId(short value) {
                            this.datumId = value;
                        }

                        /**
                         * Gets the value of the fieldType property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getFieldType() {
                            return fieldType;
                        }

                        /**
                         * Sets the value of the fieldType property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setFieldType(String value) {
                            this.fieldType = value;
                        }

                        /**
                         * Gets the value of the exampleValue property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getExampleValue() {
                            return exampleValue;
                        }

                        /**
                         * Sets the value of the exampleValue property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setExampleValue(String value) {
                            this.exampleValue = value;
                        }

                        /**
                         * Gets the value of the allowedValues property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Protocol.Category.Messages.Message.Fields.Field.AllowedValues }
                         *     
                         */
                        public Protocol.Category.Messages.Message.Fields.Field.AllowedValues getAllowedValues() {
                            return allowedValues;
                        }

                        /**
                         * Sets the value of the allowedValues property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Protocol.Category.Messages.Message.Fields.Field.AllowedValues }
                         *     
                         */
                        public void setAllowedValues(Protocol.Category.Messages.Message.Fields.Field.AllowedValues value) {
                            this.allowedValues = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="allowed_value" maxOccurs="unbounded" minOccurs="0">
                         *           &lt;complexType>
                         *             &lt;complexContent>
                         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                         *                 &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                         *               &lt;/restriction>
                         *             &lt;/complexContent>
                         *           &lt;/complexType>
                         *         &lt;/element>
                         *       &lt;/sequence>
                         *       &lt;attGroup ref="{}allowed_values_attributes"/>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "allowedValue"
                        })
                        public static class AllowedValues {

                            @XmlElement(name = "allowed_value")
                            protected List<Protocol.Category.Messages.Message.Fields.Field.AllowedValues.AllowedValue> allowedValue;
                            @XmlAttribute(name = "optional_value_allowed", required = true)
                            protected boolean optionalValueAllowed;

                            /**
                             * Gets the value of the allowedValue property.
                             * 
                             * <p>
                             * This accessor method returns a reference to the live list,
                             * not a snapshot. Therefore any modification you make to the
                             * returned list will be present inside the JAXB object.
                             * This is why there is not a <CODE>set</CODE> method for the allowedValue property.
                             * 
                             * <p>
                             * For example, to add a new item, do as follows:
                             * <pre>
                             *    getAllowedValue().add(newItem);
                             * </pre>
                             * 
                             * 
                             * <p>
                             * Objects of the following type(s) are allowed in the list
                             * {@link Protocol.Category.Messages.Message.Fields.Field.AllowedValues.AllowedValue }
                             * 
                             * 
                             */
                            public List<Protocol.Category.Messages.Message.Fields.Field.AllowedValues.AllowedValue> getAllowedValue() {
                                if (allowedValue == null) {
                                    allowedValue = new ArrayList<Protocol.Category.Messages.Message.Fields.Field.AllowedValues.AllowedValue>();
                                }
                                return this.allowedValue;
                            }

                            /**
                             * Gets the value of the optionalValueAllowed property.
                             * 
                             */
                            public boolean isOptionalValueAllowed() {
                                return optionalValueAllowed;
                            }

                            /**
                             * Sets the value of the optionalValueAllowed property.
                             * 
                             */
                            public void setOptionalValueAllowed(boolean value) {
                                this.optionalValueAllowed = value;
                            }


                            /**
                             * <p>Java class for anonymous complex type.
                             * 
                             * <p>The following schema fragment specifies the expected content contained within this class.
                             * 
                             * <pre>
                             * &lt;complexType>
                             *   &lt;complexContent>
                             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                             *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                             *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                             *     &lt;/restriction>
                             *   &lt;/complexContent>
                             * &lt;/complexType>
                             * </pre>
                             * 
                             * 
                             */
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "")
                            public static class AllowedValue {

                                @XmlAttribute(name = "value", required = true)
                                protected String value;
                                @XmlAttribute(name = "description", required = true)
                                protected String description;

                                /**
                                 * Gets the value of the value property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getValue() {
                                    return value;
                                }

                                /**
                                 * Sets the value of the value property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                /**
                                 * Gets the value of the description property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getDescription() {
                                    return description;
                                }

                                /**
                                 * Sets the value of the description property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setDescription(String value) {
                                    this.description = value;
                                }

                            }

                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="revision" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="author" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "revision"
    })
    public static class Revisions {

        @XmlElement(required = true)
        protected List<Protocol.Revisions.Revision> revision;

        /**
         * Gets the value of the revision property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the revision property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRevision().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Protocol.Revisions.Revision }
         * 
         * 
         */
        public List<Protocol.Revisions.Revision> getRevision() {
            if (revision == null) {
                revision = new ArrayList<Protocol.Revisions.Revision>();
            }
            return this.revision;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="author" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Revision {

            @XmlAttribute(name = "type", required = true)
            protected String type;
            @XmlAttribute(name = "version", required = true)
            protected String version;
            @XmlAttribute(name = "author", required = true)
            protected String author;
            @XmlAttribute(name = "date", required = true)
            protected String date;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVersion(String value) {
                this.version = value;
            }

            /**
             * Gets the value of the author property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAuthor() {
                return author;
            }

            /**
             * Sets the value of the author property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAuthor(String value) {
                this.author = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDate(String value) {
                this.date = value;
            }

        }

    }

}
