package com.ntkn.flavix;




public enum EventResult {

	EVALUATION_PASSED_AS_FIRST_EVALUATION_FOR_LONG_ENTRY,
	EVALUATION_PASSED_AS_FIRST_EVALUATION_FOR_SHORT_ENTRY,
	EVALUATION_PASSED_AS_FIRST_EVALUATION_FOR_FLAT_ENTRY,
	EVALUATION_NOTPASSED,
	ALREADY_EVALUATED,
	NOT_EVALUATED

}
